### ISSUE TITLE
faulhaber电机

### ISSUE THREAD

**Issue by zrxwz** [zZ23EcL/FH_control#1]
请问下我目前有motor 3268G024BX4 CS电机，带有速度控制器，请问下该怎么去驱动它

**Comment by zZ23EcL** [comment]
以官方手册为准

**Comment by zrxwz** [comment]
官方手册上没找到相关内容，请问下这个电机能用python吗？我打算用serial接口，但是没搞好，比如用的什么命令来让它运动

**Comment by zrxwz** [comment]
> 以官方手册为准
 我通过以前有的人写的C++看到了几个运动指令，比如’56 30 30 0D‘这样的控制转向和转速的指令，请问下这种控制指令是在哪里找的？在网上找不到相关资料，谢谢

**Comment by zZ23EcL** [comment]
> > 以官方手册为准
> > 我通过以前有的人写的C++看到了几个运动指令，比如’56 30 30 0D‘这样的控制转向和转速的指令，请问下这种控制指令是在哪里找的？在网上找不到相关资料，谢谢

你要驱动电机，请仔细查看你用的速度控制器的官方手册，速度控制器或运动控制器页面有相关命令（例如MC 5010s）

**Comment by zrxwz** [comment]
> > > 以官方手册为准
> > > 我通过以前有的人写的C++看到了几个运动指令，比如’56 30 30 0D‘这样的控制转向和转速的指令，请问下这种控制指令是在哪里找的？在网上找不到相关资料，谢谢
> 
> 你要驱动电机，请仔细查看你用的速度控制器的官方手册，速度控制器或运动控制器页面有相关命令（例如MC 5010s）
好的，谢谢你，我去查一下我的速度控制器。我最近发现再faulhaber的官方驱动上面，控制电机的时候log也有相关的控制指令，不过数据很杂，找不到有用的信息

**Comment by zrxwz** [comment]
请问有什么办法可以查看控制器型号吗？我这个实在是没有资料，我在软件驱动上查不到编码器型号，在官网上查找适配的好好几个型号

**Comment by zZ23EcL** [comment]
去硬件上找编号

**Comment by zrxwz** [comment]
> 去硬件上找编号
牛逼，简单明了
